export { default as TwoAuthIllustration } from './illustration_2FA'
export * from './illustration_404'
export { default as CreditCardIllustration } from './illustration_credit_card'
export * from './illustration_empty_data'
export * from './illustration_error_request'
export { default as PaymentCashIllustration } from './illustration_payment_cash'
export { default as PaymentTerminalIllustration } from './illustration_payment_terminal'
export * from './illustration_select'
export * from './illustration_upload'
