export const PROCESS_LIST = {
  REGISTER: 'REGISTRO',
  VALIDATION_CODE: 'CODIGO DE VALIDACIÓN',
  CONTINUE_PROCESS: 'CONTINUAR PROCESO',
  SERVICES_SELECTION: 'SELECCION DE SERVICIOS',
  COMMERCE_INFO: 'INFORMACIÓN DEL COMERCIO',
  COMMERCE_DOCUMENTATION: 'DOCUMENTOS DEL COMERCIO',
  FINISHED_PROCESS: 'PROCESO FINALIZADO'
}

export const PROCESS_LIST_STEPS = [
  { name: PROCESS_LIST.SERVICES_SELECTION, step: 1 },
  { name: PROCESS_LIST.COMMERCE_INFO, step: 2 },
  { name: PROCESS_LIST.COMMERCE_DOCUMENTATION, step: 3 },
  { name: PROCESS_LIST.FINISHED_PROCESS, step: 4 }
]
