export { ViaboCardRouter } from '@/app/business/viabo-card/routes/ViaboCardRouter'
export { ViaboPayRouter } from '@/app/business/viabo-pay/routes/ViaboPayRouter'
export { default as ViaboSpeiRouter } from '@/app/business/viabo-spei/shared/routes/ViaboSpeiRouter'
export { CatalogsRouter } from '@/app/catalogs/shared/routes/CatalogsRouter'
export { ManagementRouter } from '@/app/management/shared/routes/ManagementRouter'
export { SupportRouter } from '@/app/support/shared/routes/SupportRouter'
export { GeneralRouter } from '@/routes/GeneralRouter'
export { PublicRouter } from '@/routes/PublicRouter'
