find-companies-by-card-cloud-service:
  path: '/api/commerces/card-cloud-service'
  controller: Viabo\Backend\Controller\backoffice\projection\find\CompaniesByCardCloudServiceFinderController
  methods: GET

find-sub-account:
  path: '/api/commerce/{subAccountId}/sub-account'
  controller: Viabo\Backend\Controller\backoffice\projection\find\SubAccountFinderController
  methods: GET

find-sub-account-movements:
  path: '/api/commerce/{subAccountId}/sub-account/movements'
  controller: Viabo\Backend\Controller\backoffice\projection\find\SubAccountMovementsFinderController
  methods: GET

find-users-of-profile-card-cloud-owner-by-company:
  path: '/api/company/users/card-cloud-owners/{companyId}'
  controller: Viabo\Backend\Controller\backoffice\projection\find\CardCloudOwnersFinderController
  methods: GET

find-users-by-administrators-stp:
  path: '/api/security/users-by-admin-stp'
  controller: Viabo\Backend\Controller\backoffice\projection\find\AdminCompanyUsersFinderController
  methods: GET
